from rsf.proj import *

####################################################################
n1=101
n2=101
n3=61
h1=60
h2=60
h3=25

Flow('rhotrue',None,
	'''
	echo in=rho11 n1=%d n2=%d n3=%d data_format=binary_float |
	sfdd form=native | 
	sfput d1=%g d2=%g d3=%g o1=-3000 o2=-3000 o3=0
	label1=X label2=Y label3=Z unit1=m unit2=m unit3=m
	'''%(n1,n2,n3,h1,h2,h3))
Flow('rhoinit',None,
	'''
	echo in=rho11_init2 n1=%d n2=%d n3=%d data_format=binary_float |
	sfdd form=native | 
	sfput d1=%g d2=%g d3=%g o1=-3000 o2=-3000 o3=0
	label1=X label2=Y label3=Z unit1=m unit2=m unit3=m
	'''%(n1,n2,n3,h1,h2,h3))
Plot('rhotrue1', 'rhotrue',
	'''
	byte allpos=y gainpanel=all clip=25 minval=0 maxval=25 scalebar=y bar=bar.rsf |  
	sftransp plane=13 | sftransp plane=23 |
	grey3 flat=n frame1=%d frame2=%d frame3=%d bar=bar.rsf scalebar=y  color=j mean=y title="(a)" 
	'''%(25,62,50))
Plot('rhoinit',
	'''
	byte allpos=y gainpanel=all clip=25 minval=0 maxval=25 scalebar=y bar=bar.rsf |  
	sftransp plane=13 | sftransp plane=23 |
	grey3 flat=n frame1=%d frame2=%d frame3=%d bar=bar.rsf scalebar=y  color=j mean=y title="(b)"  
	'''%(25,62,50))

Result('rho', 'rhotrue1 rhoinit', 'SideBySideAniso')

	
Flow('grad',None,
	'''
	echo in=gradient_fwi n1=%d n2=%d n3=%d data_format=binary_float |
	sfdd form=native | 
	sfput d1=%g d2=%g d3=%g o1=-3000 o2=-3000 o3=0
	label1=X label2=Y label3=Z unit1=m unit2=m unit3=m
	'''%(n1,n2,n3,h1,h2,h3))
Flow('grad_preco',None,
	'''
	echo in=gradient_preco n1=%d n2=%d n3=%d data_format=binary_float |
	sfdd form=native | 
	sfput d1=%g d2=%g d3=%g o1=-3000 o2=-3000 o3=0
	label1=X label2=Y label3=Z unit1=m unit2=m unit3=m
	'''%(n1,n2,n3,h1,h2,h3))

iz=25
ix=62
iy=56

Plot('grad',
       '''
       byte allpos=n gainpanel=all |
       sftransp plane=13 | sftransp plane=23 |
       grey3 flat=n frame1=%d frame2=%d frame3=%d color=j mean=y title="Grad" 
       '''%(iz,ix,iy))
Plot('grad_preco',
       '''
       byte allpos=n gainpanel=all |
       sftransp plane=13 | sftransp plane=23 |
       grey3 flat=n frame1=%d frame2=%d frame3=%d color=j mean=y title="Grad_preco" 
       '''%(iz,ix,iy))

Result('final', 'grad grad_preco', 'SideBySideAniso')


Flow('rhoinv',None,
	'''
	echo in=param_final n1=%d n2=%d n3=%d data_format=binary_float |
	sfdd form=native | 
	sfput d1=%g d2=%g d3=%g o1=-3000 o2=-3000 o3=0
	label1=X label2=Y label3=Z unit1=m unit2=m unit3=m
	'''%(n1,n2,n3,h1,h2,h3))
Plot('rhoinv1','rhoinv',
       '''
       byte allpos=y gainpanel=all maxval=25 minval=0 scalebar=y bar=bar.rsf |  
       sftransp plane=13 | sftransp plane=23 |
       grey3 flat=n frame1=%d frame2=%d frame3=%d bar=bar.rsf scalebar=y  color=j mean=y title="(a)" 
       '''%(iz,44,iy))
Plot('rhoinv2','rhoinv',
       '''
       byte allpos=y gainpanel=all maxval=25 minval=0 scalebar=y bar=bar.rsf |  
       sftransp plane=13 | sftransp plane=23 |
       grey3 flat=n frame1=%d frame2=%d frame3=%d bar=bar.rsf scalebar=y  color=j mean=y title="(b)" 
       '''%(iz,ix,iy))

Result('final2', 'rhoinv1 rhoinv2', 'SideBySideAniso')

End()
